/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javacexamples;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //public String of(final OperatorEncoding<? extends Operator>... operators) {
        //PlanFragmentEncoding ret = new PlanFragmentEncoding();
        //ret.operators = Arrays.asList(operators);
    //    return null;
    //  }

    public static void main(String[] args) {
        Pointer _ = new Pointer();
        List<Map<String, Object>> roles = (List<Map<String, Object>>)_.list();
        java.util.Date myDate = new java.util.Date();
        int currentDay = myDate.getDay();
        System.out.println(new App().getGreeting());
    }
}
